
-- The Archmage Antonidas - Part II (OBJECT entry=192871)
-- Missing next_page
UPDATE page_text SET next_page = '3410' WHERE entry = '3409';

-- The Archmage Antonidas - Part III (OBJECT entry=192872)
-- Missing next_page
UPDATE page_text SET next_page = '3415' WHERE entry = '3414';

-- The Fluffy Bunny (OBJECT entry=192874)
-- Missing next_page
UPDATE page_text SET next_page = '3420' WHERE entry = '3419';

-- Blinking Rules & Regulations (OBJECT entry=192883)
-- Missing next_page
UPDATE page_text SET next_page = '3462' WHERE entry = '3461';

-- The Fate of Apprentice Argoly (OBJECT entry=192885)
-- Missing next_page
UPDATE page_text SET next_page = '3473' WHERE entry = '3472';

-- Bundle of Romantic Correspondences (OBJECT entry=192888)
-- Missing next_page
UPDATE page_text SET next_page = '3483' WHERE entry = '3482';

-- Excerpts from the Journal of Archmage Vargoth (OBJECT entry=192896)
-- Missing next_page
UPDATE page_text SET next_page = '3507' WHERE entry = '3506';

-- ------------------------------------------------------------------------- --

-- The Schools of Arcane Magic - Introduction (OBJECT entry=192708)
-- Text-Fix
UPDATE page_text SET text = 'The wondrous gift of magic can be bent to many purposes. We the learned have found that it is easiest to divide the eldritch arts into eight different categories in order to further understand the fundamentals of magic itself. Each of these categories is known as a school of magic, for they are often learned separately and mages frequently choose to specialize in one type or another. Other mages attempt to master all forms of magic, but few have achieved this lofty goal. Within this tome we will discuss each individual school of magic and some of their notable practitioners.' WHERE entry = '3359';

-- The Schools of Arcane Magic - Abjuration (OBJECT entry=192709)
-- Text-Fix
UPDATE page_text SET text = 'Practitioners of the arcane arts are often ambitious, and we frequently find ourselves in situations where magic may slip just slightly beyond our control. It is for this reason that the \'Ward\' spells exist. Ward spells are quick, potent incantations to protect the caster against a form of elemental damage - damage which is often caused by the caster attempting one of the other schools of magic. This is why studying abjuration early is so imperative.' WHERE entry = '3364';
UPDATE page_text SET text = 'One of the most renowned practitioners of Abjuration magic is Prince Kael\'thas Sunstrider. While the prince is quite formidable in all schools of magic, Kael\'thas has created a variation of Mana Shield that is practically unsurpassed in among the residents of Dalaran. Also notable is the Arcanist Doan, who has perfected a spell that combines Evocation and Abjuration to shield himself for a short time while preparing a powerful area-of-effect spell. This \'Detonate\' spell provides Doan with a degree of near invulnerability for a precious few seconds, but few mages have the capacity to cast it safely.' WHERE entry = '3365';

-- The Schools of Arcane Magic - Divination (OBJECT entry=192711)
-- Text-Fix (maybe the text is from a newer version of wow...)
-- UPDATE page_text SET text = 'I\'d like to take this time to remind my apprentices that scrying pools are not a toy. They are absolutely not to be used for displaying students of the opposite sex on a \'pay per view\' basis. Consider this your last warning.' WHERE entry = '3372';

-- The Old Wizard's Almanac (OBJECT entry=192905)
-- Text-Fix
UPDATE page_text SET text = 'The Old Wizard\'s Almanac: The Alliance\r\n\r\nAs a historically Alliance-friendly organization, one would think that the Kirin Tor might not need a guidebook outlining the Alliance races.  I feel that the opposite is true - that we can only understand the other races after truly looking inward.  - O.W.\r\n' WHERE entry = '3512';

-- ------------------------------------------------------------------------- --

-- McCarty's Notes (ITEM entry=38605)
-- Text missing
DELETE FROM page_text WHERE entry = 3107;
INSERT INTO page_text VALUES ('3107', '<The handwriting is unintelligible chicken scratch, but you can make out references to the color pink...>', '0');

-- Dusty Journal (ITEM entry=45058)
-- Text missing
DELETE FROM page_text WHERE entry = 3546;
INSERT INTO page_text VALUES ('3546', 'The first half of the journal seems to be nothing more than the ledger for Mr. Cooper\'s business. Handwritten columns of figures note the production and sale of barrels to the inhabitants of Moonbrook and even a few clients in Stormwind itself.\r\n\r\nThe back half of the book seems to have been Mr. Cooper\'s journal, where he discusses leaving the family business to his younger brother. You find no mention of children.', '0');

-- A Steamy Romance Novel: Blue Moon (ITEM entry=54291)
-- All texts missing
DELETE FROM page_text WHERE entry in (3622, 3623, 3624);
INSERT INTO page_text VALUES ('3622', 'Tail swooshing and hips swaying, the curvy figure walked purposefully across the lake toward the man resting by the shore; rising quickly as she approached, he appeared visibly happy to be in her presence.  Blue arms flowed over his shoulders as a smooth tail coiled seductively around his waist.  \"Why must I travel so far to be meeting man like you?\"  Her voice carried a strong, alluring accent.\r\n\r\nGrinning wildly, he gently pushed her away, openly staring as the light caught her features.\r\n\r\n\"Up here!\", she exclaimed in playful anger.\r\n\r\nWith a helpless shrug, he reached into his pack and pulled out a small pouch.  \"My wonderful Soola, I\'ve brought you something.\"  Confidence wrapped his words like a steel blanket.', '3623');
INSERT INTO page_text VALUES ('3623', 'She plucked the tiny bag from his hands, excitedly pulling it open and revealing a citrine pendant.\r\n\r\n\"Oh... Marcus, you shouldn\'t have.\"\r\n\r\nThe usual teasing was gone from his voice, \"Every facet lights the sky, and my heart, with your beautiful reflection.\"\r\n\r\nSoola frowned.  \"Uh... no. I meant you really shouldn\'t have.  I could craft something better by accident.\"\r\n\r\nFor the first time, possibly ever, Marcus looked hurt.  His shoulders slumped slightly, the cocky, ever-present grin missing from his handsome face.\r\n\r\nSoola opened her mouth to speak, smiling warmly; a glowing rune appeared above her eyes.  \"I don\'t think I can mend your feelings, even with my Gift.\"', '3624');
INSERT INTO page_text VALUES ('3624', 'Despite the statement, her words seemed to do the trick.  Marcus smirked roguishly as he adjusted his leg plates, \"Well you aren\'t the only gifted one.\"\r\n\r\nSilence penetrated the room with palpable force as the conversation shifted to the language shared by all races of Azeroth.\r\n\r\nMinutes became hours, until their passionate dialog was interrupted by lightning streaking from the cloudless sky, thunderously slamming into the lake\'s surface and bathing them in steam.\r\n\r\n\"Is something wrong?\", Marcus asked.\r\n\r\n\"No my Marcus, you\'re just off to a great start...\"\r\n\r\nThe remaining pages have been thoroughly destroyed by the elements.', '0');

-- ------------------------------------------------------------------------- --

-- First History Scroll (OBJECT entry=192493)
-- Text missing
DELETE FROM page_text WHERE entry = 3280;
INSERT INTO page_text VALUES ('3280', 'Long ago, when the North Wind ruled these peaks alone, a powerful taunka chieftain\'s brother coveted these lands for himself.', '0');

-- Second History Scroll (OBJECT entry=192494)
-- Text missing
DELETE FROM page_text WHERE entry = 3281;
INSERT INTO page_text VALUES ('3281', 'The chieftain\'s brother, Stormhoof, gathered all his strength and set out to conquer the Storm Peaks from its rightful ruler, the North Wind.', '0');

-- Third History Scroll (OBJECT entry=192495)
-- Text missing
DELETE FROM page_text WHERE entry = 3282;
INSERT INTO page_text VALUES ('3282', 'Stormhoof ambushed the North Wind in the heart of its domain, and nearly succeeded in his plot. But the North Wind survived Stormhoof\'s treachery and executed the taunka as punishment for his invasion.', '0');

-- Damaged Apprentice Journal (OBJECT entry=192651)
-- All texts missing
DELETE FROM page_text WHERE entry in (3284, 3285, 3286, 3287, 3288, 3289, 3290, 3291, 3292, 3293, 3294, 3295, 3296, 3297, 3298, 3299, 3300, 3301);
INSERT INTO page_text VALUES ('3284', '<The majority of the book\'s pages are missing or soiled beyond recovery. A few of the early entries and the name \'Darius Orion\' are still legible.>', '3285');
INSERT INTO page_text VALUES ('3285', 'Dec. 2 of the Year 20\r\n\r\nThe cold this year has been particularly cruel. I find that no matter how many layers I wear under my robes, the frost cuts deep into my bones. The masters say that it will pass but I have trouble believing that at times.\r\n\r\n\r\n', '3286');
INSERT INTO page_text VALUES ('3286', 'A small group of workers from an outlying farm near Andorhal were brought in this morning and taken to the infirmary within the Violet Citadel. I do not know much about what ails them but I overheard one of them complaining about weakness and nausea. I hope the masters choose me to aid them in working to treat the farmers.', '3287');
INSERT INTO page_text VALUES ('3287', '2 hours later\r\n\r\nWhat luck!  One of the masters informed me that I will be working with the men who were brought in from Andorhal earlier. I intend to make good use of this opportunity to show how far I have come in my studies.\r\n', '3288');
INSERT INTO page_text VALUES ('3288', '6 hours later\r\n\r\nThis is not turning out to be quite as glorious as I had planned. The farmers\' conditions have deteriorated quickly in their short time here. One has developed irritated boils covering large portions of his skin. I have treated the most seriously afflicted with some of the most powerful herbs and poultices available in the citadel. There should be some noticeable improvement within the next few hours.\r\n', '3289');
INSERT INTO page_text VALUES ('3289', '10 hours later\r\n\r\nThe situation has quickly gotten out of control.  All of the subjects are now covered in lesions which leak yellow-green fluid. All but a few are unconscious at this point. The few that are awake alternate between complaints of paralyzing numbness and burning aches in their joints. All of the subjects are showing a milky coloring in their eyes.\r\n', '3290');
INSERT INTO page_text VALUES ('3290', 'Our attempts to slow the progress of the illness have been unsuccessful. Word has spread among the apprentices that this disease may be magical in nature; the masters were quick to quash the rumors. Many of the other apprentices that I had been working with on this project have excused themselves for fear that the disease is contagious and capable of penetrating our personal wards.\r\n\r\n\r\n\r\n', '3291');
INSERT INTO page_text VALUES ('3291', 'I excused myself to take a walk out on one of the terraces to clear my thoughts. I could not have been outside for more than a couple minutes when I had to run back inside. My hands and feet had gone numb and my nose and ears were showing the symptoms of mild exposure to frostbite. I will have to be more careful next time.', '3292');
INSERT INTO page_text VALUES ('3292', '13 hours later\r\n\r\nLight save us.\r\n\r\nThe subjects have begun severe hemorrhaging from the eyes and ears. The masters believe they will all be dead within the hour. All attempts to halt the progress of the disease have failed. I have done what I can to ease their pain. I only hope that we can learn what we need from them after their deaths. No one should suffer as these men have suffered. I plan to stay with them until the end.\r\n', '3293');
INSERT INTO page_text VALUES ('3293', 'To make matters worse one of the guards found the body of a first year apprentice in the gardens. It has not been confirmed yet but the rumors are that he froze to death. I do not think it has been this cold here in Dalaran in decades, if ever.\r\n', '3294');
INSERT INTO page_text VALUES ('3294', '18 hours later\r\n\r\nThe farmers from Andoral are dead. I thought they would finally be at peace but I was wrong. Only a few minutes after the last one breathed his last breath something horrifying happened. Their disease riddled corpses somehow animated and began clawing at myself and the other mages in the infirmary. Once the initial confusion passed one of the masters organized a force to deal with the animated bodies. The undead quickly fell to our combined arcane might.\r\n', '3295');
INSERT INTO page_text VALUES ('3295', 'There were minimal casualties. A few of the apprentices had been scratched; one had a nasty bite that required stitches. Shortly afterward guards arrived and escorted myself and the other apprentices to our rooms. I tried to learn what was going on but they would not answer me. As we were being led through the halls to our rooms we passed by several troupes of guards with weapons drawn and readied. Is this what war feels like?\r\n\r\n\r\n', '3296');
INSERT INTO page_text VALUES ('3296', 'After I was brought to my room I was told to lock the door and not come out until I was told by a master personally that it was safe to leave. What is going on?  Has the world gone mad?', '3297');
INSERT INTO page_text VALUES ('3297', '24 hours later\r\n\r\nI have been awake for over twenty-four hours now. I am exhausted but my room is too cold to sleep. I managed to complete a sending and contact a couple of the other apprentices who are trapped in their rooms. Through them I was able to learn what has the citadel on high alert. The masters are organizing search parties to locate the necromancer who was responsible for animating the corpses of the diseased farmers.\r\n', '3298');
INSERT INTO page_text VALUES ('3298', 'There has not been a practicing necromancer in Dalaran since Kel\'Thuzad. I hope the monster responsible for the horrors I have seen today is brought to justice soon.\r\n', '3299');
INSERT INTO page_text VALUES ('3299', '38 hours later\r\n\r\nThe quarantine has been lifted and we apprentices are finally allowed to leave our rooms. The necromancer responsible for animating the dead farmers was never caught but the masters are confident that he is not within the citadel or anywhere near Dalaran. \r\n', '3300');
INSERT INTO page_text VALUES ('3300', 'We have resumed our efforts to learn more about the disease. Work has been slow due to most of the bodies having been obliterated. The masters have called in Lady Jaina Proudmoore to aid in our research. She will teleport here by the end of the day. I hear she is quite beautiful; hopefully working with Lady Proudmoore with help me keep my mind off of this damned cold.\r\n', '3301');
INSERT INTO page_text VALUES ('3301', '<The journal is too badly damaged to read beyond this point.>', '0');

-- The Worst Mage in Dalaran: A Children's Book (OBJECT entry=192706)
-- All texts missing
DELETE FROM page_text WHERE entry in (3346, 3347, 3348, 3349, 3350, 3351, 3352);
INSERT INTO page_text VALUES ('3346', 'Once upon a time there lived a mage who could not cast fireball, polymorph, or frostbolt. When he conjured water, it came out as mud. His attempts at arcane intellect made the subjects stupider. Without any doubt, his tutors agreed that their pupil, Bungledorf, was the worst mage in Dalaran.', '3347');
INSERT INTO page_text VALUES ('3347', 'Bungledorf had come to learn with great hopes. He guzzled mana potions before class, mistakenly believing they would increase his skill. But all they ever increased was the number of times he accidentally burped during important invocations, often setting classmates\' robes ablaze or turning his teacher\'s beard into sheep\'s wool in the process.', '3348');
INSERT INTO page_text VALUES ('3348', 'At his first exam, Bungledorf was asked to cast frost armor correctly. The other students shifted in their seats fearfully as he began the incantation. A blue fog encompassed the young lad and for a moment it looked as though he had succeeded. But then he began to shiver and sneeze violently, and everyone finally realized: he had given himself frostbite.', '3349');
INSERT INTO page_text VALUES ('3349', 'One day Bungledorf was in the park, wondering whether he was cut out to be a mage. He saw some children playing nearby and remembered his dream of being a powerful spellcaster. \"Yes,\" he thought, \"I can do it; I just need to try harder!\" He looked for something to practice on and noticed an unusual tree before him. Summoning his courage, Bungledorf began casting a spell on it. He shut his eyes, afraid to see the result...', '3350');
INSERT INTO page_text VALUES ('3350', 'When he finally looked, the tree was replaced with a beautiful night elf. \"It worked!\" he cried, \"It\'s transformed! I am a mage after all!\"\r\n\r\nThe night elf was confused for a moment and then smiled at him gently. \"I am a druid, young one. We take other forms by our own will.\"', '3351');
INSERT INTO page_text VALUES ('3351', 'Bungledorf blushed and stepped away, only to trip over his robes and fall headfirst into the lawn. A chorus of giggles greeted him as he adjusted his long pointed cap and shuffled off toward the dormitory, his head hanging low.', '3352');
INSERT INTO page_text VALUES ('3352', 'The night elf lingered, pondering the boy. When she turned to leave, she caught her foot in something, and nearly lost her balance. Surprised at the unfamiliar obstacle, she looked down to see a glistening crop of mageroyal, its petals slowly unfurling into full bloom, where moments ago there had been nothing. She wondered at this, and then, realizing, turned back in the direction Bungledorf had been walking, but the young mage was already gone.', '0');

-- Weathered Diary - Dates from the Third War (OBJECT entry=192707)
-- All texts missing
DELETE FROM page_text WHERE entry in (3353, 3354, 3355, 3356, 3357);
INSERT INTO page_text VALUES ('3353', 'Entry 1\r\n\r\nBefore I could understand what was happening, the devastation was upon us. The ground trembled and our fair spire, which had stood citadel over Dalaran since the Second War, shattered.\r\n\r\nI remember screaming as my father\'s face disappeared behind the tumbling scaffolding, but I heard nothing. Even in my terror, I thought of my magical training. If I could only slow this disaster-but the spells died within me. Traces of demonic power barred my efforts. There was no hope. I closed my eyes and waited. But somehow, I am still here.', '3354');
INSERT INTO page_text VALUES ('3354', 'Entry 2\r\n\r\nThe wreckage shifted for hours. I was certain each new thundering tremor would finally end it. Instead, I remain huddled beneath an archway that had once framed our view of the bustling market streets. How many times had I seen my sister returning from there, her arms loaded with goods? Now only dust and stone stand before me.', '3355');
INSERT INTO page_text VALUES ('3355', 'Entry 4\r\n\r\nI must believe in the Kirin Tor. The great mages of Dalaran would not desert their people. This rubble that imprisons me is no more than a trifle to a skilled spellcaster. I will be saved, and one day, I will finish my training and stand among them.', '3356');
INSERT INTO page_text VALUES ('3356', 'Entry 5\r\n\r\nThere are no signs of others or of my family. I have called for them. Everything above is silent now. I am not sure whether I am blessed or cursed. My heart would quiet itself and follow the others to rest, but my mind is thick with fear.', '3357');
INSERT INTO page_text VALUES ('3357', 'Entry 6\r\n\r\nIt grows darker and the air is thinner. The faint lights I summon to write burn into my eyes. I can do no more. My energy must be saved for what may yet come. I am audacious enough to hope that these scraps of paper will hold out against the silence as I cannot. I would become a voice, singing up through this abyss, softening until a whisper, and then fading into the sky.', '0');

-- LAVA BLAST - by Pyroco (OBJECT entry=192869)
-- All texts missing
DELETE FROM page_text WHERE entry in (3398, 3399, 3400, 3401, 3402);
INSERT INTO page_text VALUES ('3398', 'Feeling a little down? Need some energy? How about lots of energy? What about some hot, fiery incendiary energy?\r\n\r\nTry the new LAVA BLAST from Pyroco.  You\'ll fall in love with its sweet, refreshing taste and the  raw power within. Need a quick pick me up? No problem! LAVA BLAST will rejuvenate you even at your most exhausted. ', '3399');
INSERT INTO page_text VALUES ('3399', 'Severely injured? We\'ve got you covered! LAVA BLAST will give you that extra energy you need to find your way to safety!*\r\nDo you love fire? Have you ever thought about how awesome it would be to drink liquid fire? If so, you\'ll love new LAVA BLAST  from Pyroco! Taste the burning!\r\n\r\n*Recent studies have shown that Lava Blast may not actually assist in healing wounds in any way. There is a possibility that Lava Blast may actually cause you to bleed profusely from seemingly random orifices.', '3400');
INSERT INTO page_text VALUES ('3400', 'Warning:  Lava Blast is not for everyone. Pregnant women, children, and women who might become pregnant or are nursing should consult their doctors before drinking Lava Blast.\r\n', '3401');
INSERT INTO page_text VALUES ('3401', 'Possible Side Effects May Include: Dry mouth, upset stomach, dry eyes, indigestion, back pain, bone and joint pain, slight disfiguration, internal bleeding, temporary insanity, Lava Blast addiction, magic addiction, pyromania, fear of spiders, lightning eyes, heart palpitations, fever, spontaneous child birth, lack of sleep, vulnerability to cold iron, hysteria, random songs popping into your head, asthma, demonic possession, headaches, footaches, the inability to use the letter \'R\', and death.\r\n', '3402');
INSERT INTO page_text VALUES ('3402', 'Caution: Drinking multiple Lava Blasts in rapid succession can result in spontaneous combustion.\r\r\n\nTry new LAVA BLAST now!', '0');

-- The Archmage Antonidas - Part I (OBJECT entry=192870)
-- All texts missing
DELETE FROM page_text WHERE entry in (3403, 3404, 3405, 3406, 3407, 3408);
INSERT INTO page_text VALUES ('3403', 'Antonidas was but a mere boy when he became an apprentice to one of the Kirin Tor.  He was a tenacious learner, pouring over books in the magical libraries of Dalaran.  After only a few short years of studying under the sect, Antonidas had outclassed his peers and earned their admiration, as well as the respect of his elders.\r\n', '3404');
INSERT INTO page_text VALUES ('3404', 'At the age of 12, Antonidas\' thesis, The Ramifications of Refining Reverse Time Travel Phenomena into Quantifiable Magical Practice earned him the Kirin Tor Sash of Supreme Acumen, the youngest ever to receive the award. Shortly thereafter the Ruling Council offered him official placement in the Kirin Tor Advanced Research and Illumination Sect, also the youngest to receive an official invitation.', '3405');
INSERT INTO page_text VALUES ('3405', 'As the mage grew older, he continued to learn and hone his abilities.  His natural talent for defensive magic and wisdom beyond his years made Antonidas an ideal candidate for a position on the Council of Six, which he eventually attained.  Antonidas proved not only wise and fair, but infinitely regimented in goal to become more knowledgeable. He quickly became one of the dominant voices of Dalaran.', '3406');
INSERT INTO page_text VALUES ('3406', 'Before the Second War, leaders of each of the Azerothian nations met in Lordaeron to discuss the threat of the orc invasion.  Archmage Antonidas attended the summit on behalf of the Council of Six, pledging loyalty to the Alliance on Dalaran\'s behalf. He also monitored the progress of the young but extremely talented mage Khadgar, who had served as Medivh\'s apprentice during the first war.  In the aftermath of the Second War, Antonidas promoted Khadgar to the rank of archmage and placed him in a position of authority over the mission to enter the Dark Portal and investigate Draenor.', '3407');
INSERT INTO page_text VALUES ('3407', 'After the Second War, Antonidas investigated the lethargy of the orcs.  The archmage published several theses on his research:\r\n\r\nThe Causality of War: A Comprehensive Study on Orc Lassitude.\r\n\r\nThe Contrast of Orc Tradition, Sociology, and Psychological Practices from Before and After the Second War.\r\n\r\nEmpirical Study on the Formulation and History of High Profile Fel Magics, and their Relation to the Orc Race.', '3408');
INSERT INTO page_text VALUES ('3408', 'The consensuses of many of these reports are largely inconclusive. Antonidas himself has said on occasion that finding a cure for the malaise of the orcs would be an almost unachievable venture. His formal conclusion was that the orcs\' only path to a healthy lifestyle would be a spiritual one.', '0');

-- Journal of Archmage Antonidas (OBJECT entry=192880)
-- All texts missing
DELETE FROM page_text WHERE entry in (3432, 3433, 3434, 3435, 3436, 3437, 3438, 3439, 3440, 3441, 3442);
INSERT INTO page_text VALUES ('3432', 'Oct 8.\r\n\r\nAs I have said before, I am becoming increasingly disturbed by the dangerously vast potential of certain schools of magic, and the contrasting amount of laws and boundaries that should be set to limit them. Furthermore, comprehensive research on these volatile schools shows a trend of decreasing academic prerequisites yielding increasingly powerful outcomes. \r\n', '3433');
INSERT INTO page_text VALUES ('3433', 'A student of mine asked me today, \"Why are there so many limitations on traditional portals, when Fel portals can be made twice as large and last ten times as long?\" The student was not yet educated in the abstraction of what is practical versus what is achievable, yet the question held within me a certain duality: What future is there for the established practices of magic when so many wild variations threaten to overshadow them? \r\n', '3434');
INSERT INTO page_text VALUES ('3434', 'I do all I can to stifle studies of Fel magics and necromancy here, yet I find myself both disturbed and enthralled by their potential. I refuse to believe that that their efficiency so soundly trumps the common criticisms of being unstable or \"evil\" that these schools hold the monopoly of avenues for magical progress. Yet when witnessing the massive infernal for one\'s self, or seeing acres of land blighted at the wave of a hand, I fear my beliefs may soon shift from gospel to dogma in the minds of my peers.\r\n', '3435');
INSERT INTO page_text VALUES ('3435', 'Oct 16.\r\n\r\nMy primary focus has shifted to research of the plague that ravages the north. I\'ve canceled most of my classes to focus on research of this terrible anomaly. \r\nWith immense precaution I\'ve procured a shipment of the infested grain. Immediately I was both impressed and suspicious with how innocuous the whole package presented itself. There was no discoloration, no discernable odor, and no variation at all from any other sheaf of grain. \r\nAt that moment it was no longer a mystery how this plague spread so quickly. \r\n', '3436');
INSERT INTO page_text VALUES ('3436', 'Oct 17.\r\nFurther study of the plague has yielded disturbing conclusions, and even more disturbing implications. \r\nInitial testing showed the plague had only minor effects on non-human creatures. Symptoms ranged from fatigue, nausea, fever, to minor hallucinations, but rarely resulted in death. On human tissue, however, the plague acts uniformly and with unprecedented expediency towards necrosis.\r\n', '3437');
INSERT INTO page_text VALUES ('3437', 'It would be foolish to think that such an efficient human killer only being found in human rations is a coincidence. While it\'s certainly possible that these two occurrences are unrelated, I\'ve decided to delegate more resources towards finding the source of this plague, for I fear there are intelligent hands pushing it upon our kin. \r\n\r\nMore research must be done here at Dalaran, however. I will decide who to send to investigate in my stead at a later date, after some heavy deliberation. ', '3438');
INSERT INTO page_text VALUES ('3438', 'Oct 18.\r\n\r\nI\'ve stumbled upon a key factor of this plague, one so cleverly hidden in its methodology that I\'ve come to two immutable conclusions: That its development was for the singular purpose of ending human life, and its inception was at the hands of an intelligent being. \r\nLong term affliction of the plague causes a certain reanimation of activity in the dead. This activity is very small at first, and I disregarded it as a minor side-effect. However, this energy remained persistent and unwavering. A thought struck me, one which was both surprising and strong: The corpse was waiting for something. \r\n', '3439');
INSERT INTO page_text VALUES ('3439', 'At that moment I did not have any evidence to prove it, but I nonetheless I spent time pursuing it. I used my limited knowledge of necromancy and casted simple curses on the corpse. At the time I had no motivation to raise the dead, only to change or distinguish the radiating energy off the corpse. Imagine my surprise when it sprung to life and attacked me.\r\n', '3440');
INSERT INTO page_text VALUES ('3440', 'I did not hesitate to incinerate it to dust, and I now I regret doing so. But I was able to prove my unprovoked theory, that the corpse (and by extension the plague that saturates it) was indeed waiting for further commands. It\'s clear that those who die by this plague are only lying dormant in their graves, awaiting one skillful in necromancy to awaken them.\r\n\r\n In short, it is indisputable that the plague is magical in nature.  \r\n', '3441');
INSERT INTO page_text VALUES ('3441', 'Oct 20.\r\n\r\nI have decided to send my most trusted disciple, Jaina Proudmoore, to investigate the source of the plague. Based on my research, I believe only my most skillful disciple will be able to handle the unknown challenges that await such an endeavor. She will take with her a copy of this journal and my other research documents regarding the plague. Indeed I will make it public, for all people need to become aware of this imminent threat. \r\n', '3442');
INSERT INTO page_text VALUES ('3442', 'I only wish I could investigate it myself, but Terenas has proven to be predictably stubborn to my requests. It is paramount that I convince him to quarantine the north. Little else matters at this point in time. Regardless, I have the fullest faith in Jaina\'s cunning. If she or I cannot put an end to this infestation, I doubt anyone can.\r\n\r\n-Antonidas-\r\n<This is marked with the seal of the Council of Six>\r\n', '0');

-- Polymorphic Rules & Regulations (OBJECT entry=192882)
-- All texts missing
DELETE FROM page_text WHERE entry in (3454, 3455, 3456, 3457, 3458, 3459, 3460);
INSERT INTO page_text VALUES ('3454', 'Species altercation has the highest potential for abuse and disaster, and is the source of the most number of complaints to the Kirin Tor. Polymorphic study has been under constant scrutiny and threat of removal for years, but only recently have these tribulations increased exponentially. In order for this spell to continue to be sanctioned, certain guideless must be put in place to throttle the increasing number of tragedies reckless polymorphs have caused.   \r\n', '3455');
INSERT INTO page_text VALUES ('3455', 'Rule# 1: Do not turn a creature of lesser intelligence into a creature of higher intelligence - Cerebral brain function rarely translates in a polymorph... but sometimes it does. Voracious creatures such as serpents and wolves need not have their predatory instincts honed with a human mind. We feel obligated to quote Small Claims Disaster Case 12651-b, labeled, \"Bartholomew: The Bear Who Bears Arms.\"', '3456');
INSERT INTO page_text VALUES ('3456', 'Rule #2: Use simplified creatures for polymorphs - Many rogue mage disciples sanction exotic creature polymorphic studies, but in a desperate effort to lower Kirin Tor insurance claims we are ceasing to support these types of creatures. Sheep are acceptable creatures for any situation, but there are several other common creature types that are supported (read the latest edition of Kirin Tor Monthly for an up-to-date list). Polymorphing into creatures like oozes, ethereals, silithid, and worst of all dragonkin is severely punishable. Which brings us to...\r\n', '3457');
INSERT INTO page_text VALUES ('3457', 'Rule #3: Polymorphic debaucheries are to be disposed of in a timely and DISCRETE manner -The public need not bear witness to the horrendous abominations wrought from a botched polymorph. Accidents happen, and the Kirin Tor understands this. However public viewings of creatures like the were-whale, mur-elf, amphibious worgen, flying ooze, grypho-hippo-wyvern, Qiraji bunny, and the infamous \"blue-checkered cube\" give us all a bad reputation. \r\n', '3458');
INSERT INTO page_text VALUES ('3458', 'Rule #4: Do not polymorph a creature into another more powerful creature - While this looks like plain common sense, we feel obligated to quote Mildly Severe Claims Disaster Case 8761-e, labeled, \"Magus John Quint: Liquefied By Sickly Deer Turned Violently Confused Molten Giant.\"\r\n', '3459');
INSERT INTO page_text VALUES ('3459', 'Rule #5: Do not polymorph anything that is halfway through a portal - This has yet to not cause an explosion. This is also covered in \"Thinking with Portals: A Memorandum on Proper Portal Usage.\"\r\n', '3460');
INSERT INTO page_text VALUES ('3460', 'Rule #6: Do not polymorph inanimate objects! - We can\'t believe the Kirin Tor is receiving reports of this, but such a heinous act caused the development of the brand new Highly Severe Claims Disaster Case 1-a, \"My Kingdom For a Horse: The One Hundred and Fifty Reasons Why a Kingdom Should Not Be Turned Into a Horse.\"\r\n<This goes on for hundreds of pages>\r\n', '0');

-- Portals are NOT Garbage Bins! (OBJECT entry=192884)
-- All texts missing
DELETE FROM page_text WHERE entry in (3469, 3470, 3471);
INSERT INTO page_text VALUES ('3469', 'As you are all well aware, we as an organization make a regular habit of combing the local reaches of the twisting nether for misplaced objects. This has turned up all manner of wayward treasure, from errant magical essences to crackling shards of mystic power to entire suits of armor and powerful weaponry. Increasingly of late, however, we have also begun to turn up garbage and refuse as well.\r\n', '3470');
INSERT INTO page_text VALUES ('3470', 'The sheer vastness of the nether is no excuse for using it as a garbage repository! Your Portal and Teleport spells are a great privilege and responsibility, and carelessly casting the waste from your noontime meals into a portal could have GRAVE CONSEQUENCES for all of Azeroth! Please secure all objects when traveling via portal and report any lost objects to the Kirin Tor council at once. Read the latest edition of \'Thinking with Portals - A Memorandum on Proper Portal Usage\' for all information regarding portal use.', '3471');
INSERT INTO page_text VALUES ('3471', 'If this problem grows any further out of hand, I will be forced to insist that all portal travelers relinquish their weaponry and personal hygiene supplies before embarking. And the next time my lecture notes appear among the rubbish, I will personally transform the heads of all apprentices into dunce caps!\r\n\r\n--Archmage Runeweaver \r\n', '0');

-- In Time, the Arcane Corrupts All! (OBJECT entry=192886)
-- All texts missing
DELETE FROM page_text WHERE entry in (3477, 3478);
INSERT INTO page_text VALUES ('3477', '<This flier was recently pasted here. Residue of glue on the stone shows that many fliers have previously occupied this location.>\r\n', '3478');
INSERT INTO page_text VALUES ('3478', 'Hark!\r\n\r\nMagic is not what you have been taught. Its dangers far exceed the greatest gifts it may bring! Question your Elders, that you may know the truth. Act now while there is time to save yourselves! Learn the ways of Nature and share in the balance of all things, ere your destructive ways upset it beyond repair.\r\n\r\n<An unfamiliar seal decorates the bottom of the flier.>\r\n', '0');

-- Losses of the Third War (OBJECT entry=192887)
-- All texts missing
DELETE FROM page_text WHERE entry in (3479, 3480, 3481);
INSERT INTO page_text VALUES ('3479', 'Thule Ravenclaw\r\n\r\nThough accounts vary wildly, many recent  events transpiring in Tirisfal Glades and Silverpine Forest seem to indicate that Thule Ravenclaw had willingly sided with the Scourge. The husk of Fenris Keep on Lordamere Lake may yield clues, but our attention must remain elsewhere at present.\r\n', '3480');
INSERT INTO page_text VALUES ('3480', 'Gunther Arcanus\r\n\r\nPresumably killed during the events of the third war and lost to the Scourge.\r\n\r\nGunther was last in possession of my favorite pipe. Should his remains turn up, I would be most gracious for its return!\r\n', '3481');
INSERT INTO page_text VALUES ('3481', 'Bethor Iceshard\r\n\r\nKilled during the events of the third war. Bethor is known to have risen as a member of the Forsaken and should be treated as an agent of the Horde in all dealings.\r\n', '0');

-- Kirin Tor Monthly (November Issue) (OBJECT entry=192889)
-- All texts missing
DELETE FROM page_text WHERE entry in (3487, 3488, 3489);
INSERT INTO page_text VALUES ('3487', 'Dalaran Dining Guide\r\nWhen Inzi Charmlight opened A Hero\'s Welcome shortly after the city relocated, locals and visitors alike lined up to lay their weapons down and sink their teeth into a tough hunk of bread!  Seating is ample, prices are fair and the full bar offers indulgences from all over the world to help you feel satisfyingly heroic.  No matter what you order, save room for the Mead-Basted Caribou!\r\n', '3488');
INSERT INTO page_text VALUES ('3488', 'For regional fare in a less boisterous setting, try the Hocus Pocus Inn near the center of town.  The open, airy inn is easy to find and serves light meals with pleasant conversation in a relaxed, library-like atmosphere.  The regulars are primarily exhausted students of the arcane; no wonder the real star of the show is the incredibly skilled food that prepares and cooks itself at your table!\r\n', '3489');
INSERT INTO page_text VALUES ('3489', 'If you are looking for a bed, a bar and not much else, look no further than the Filthy Animal!  The bar area is dark and authentically malodorous, replete at all hours with individuals of questionable character.  The menu boasts such delicacies as Briny Hardcheese and it would take an army of enchanted dancing mops and buckets to make the sleeping quarters habitable.  A Horde paradise indeed!\r\n', '0');

-- STAY OUT!!! (OBJECT entry=192890)
-- All texts missing
DELETE FROM page_text WHERE entry in (3490, 3491, 3492, 3493, 3494, 3495, 3496);
INSERT INTO page_text VALUES ('3490', '<The worn journal\'s entries are separated by illegible or missing sheets.>\r\n\r\nWhat would Nikolai think?  I wouldn\'t dream of telling him about the voice, but I can barely speak around him anyway.  Perhaps the voice is my conscience...\r\n', '3491');
INSERT INTO page_text VALUES ('3491', '...It\'s not so much an echo as it is a comforting voice in my head, reassuring me that there\'s more to come.  It feels like the opposite of a headache (if that makes any sense), a wave of warmth and ideas.  For example: I knew the librarian kept some materials secret, but the voice tells me she has demonic literature and that even so, her understanding of demons is laughable at best.', '3492');
INSERT INTO page_text VALUES ('3492', 'My conscience was right again.  I am more than adept at the simple spellwork they teach us at school.  For every biscuit my peers conjure, I can make a meal.  Nikolai can see the change within me.  Is he scared?  My conscience tells me that\'s what the elder mages call respect.', '3493');
INSERT INTO page_text VALUES ('3493', 'I could seek him out... he\'s surely in the north!  I can see the way clearly.  Redemption can\'t be impossible.  It can\'t be too late.  I can make him whole again, or better!  With my powers growing, amplified, I can make us all so happy!  Mother, Father, Nikolai... we can all be one, together...\r\n', '3494');
INSERT INTO page_text VALUES ('3494', 'Nikolai fears me; his eyes betray what his lips won\'t say.  It\'s fine; our history and my conscience agree that respect and fear are the same.  If he leaves me, I\'ll make sure that whoever dares to touch what\'s mine lives to regret it.  They\'ll all be ours in the end, my sisters.\r\n', '3495');
INSERT INTO page_text VALUES ('3495', '  ...with threats to report or expel me if I don\'t return his cat to normal.  What\'s abnormal about an old cat?  I would have liked to do it to him instead.  How dare they defend him when he stood up to me in front of Nikolai?\r\n', '3496');
INSERT INTO page_text VALUES ('3496', 'Mother had the nerve to scold me.  Doesn\'t she realize who I am?  I can feel him calling to me.  This city and these people don\'t deserve me.  More than enough of the provisions I\'d need are in the kitchen.  Nikolai, Mother, even that blasted cat... they\'ll do anything I want and stay with me forever.  The money in Mother\'s dresser is mine by right; only I can help him.\r\n\r\n<The rest of the pages are empty.>\r\n', '0');

-- Remedial Magic 101: Tips from the Pros (OBJECT entry=192894)
-- Missing text + Text-Fix
DELETE FROM page_text WHERE entry in (3500, 3501);
INSERT INTO page_text VALUES ('3500', '- Fight fire with fire!  Just because a monster\'s body is completely made of flames doesn\'t mean that your fireball spell won\'t work.  Give it a shot!  The results might surprise you.\r\n\r\n- Dress for success!  Studies show that mages who pay attention to their wardrobe are FAR more effective than those who wear older, lower-quality clothing.  Have you updated your robe lately?\r\n\r\n- Know your role!  At first glance, your staff may look like an effective melee weapon, but it\'s not.  Let the guys with the big shiny armor stand in front.  That being said...\r\n', '3501');
INSERT INTO page_text VALUES ('3501', '- Friendly fire!  Don\'t doubt yourself - go ahead and cast that spell!  It\'s OK if you miss; your arcane missiles probably won\'t hit your friends.\r\n\r\n- Get a job!  A great way to build your skill is to ask people if they need any help with anything.  You\'d be surprised how many people are looking for a good mage to hire!  Contrary to what you might think, even the simplest act of delivering a package can make you a better caster.\r\n\r\n- The daily grind!  You may have heard about some mages choosing to mindlessly and repetitively kill monsters - often several at a time - in order to practice their spellcasting.  While this is a legitimate and often effective method to become more powerful, over extended periods of time, it will rot your brain.\r\n', '0');

-- --------------------------------------------------------------------------------- --
