INSERT INTO worldstate_name(Id, Name) VALUES
(3559,'Strand of the Ancients - Timer Minutes'),
(3560,'Strand of the Ancients - Timer Seconds Second Digit'),
(3561,'Strand of the Ancients - Timer Seconds First Digit'),
(3564,'Strand of the Ancients - Timer Enabled'),
(3571,'Strand of the Ancients - Bonus Timer'),
(4352,'Strand of the Ancients - Attacker Alliance'),
(4353,'Strand of the Ancients - Attacker Horde'),
(3614,'Strand of the Ancients - Purple Gate State'),
(3617,'Strand of the Ancients - Red Gate State'),
(3620,'Strand of the Ancients - Blue Gate State'),
(3623,'Strand of the Ancients - Green Gate State'),
(3638,'Strand of the Ancients - Yellow Gate State'),
(3849,'Strand of the Ancients - Ancient Gate State'),
(3635,'Strand of the Ancients - Left Graveyard Alliance'),
(3636,'Strand of the Ancients - Right Graveyard '),
(3637,'Strand of the Ancients - Center Graveyard '),
(3633,'Strand of the Ancients - Left Graveyard'),
(3632,'Strand of the Ancients - Right Graveyard'),
(3634,'Strand of the Ancients - Center Graveyard'),
(3627,'Strand of the Ancients - Right Attack Token Alliance'),
(3626,'Strand of the Ancients - Left Attack Token Alliance'),
(3628,'Strand of the Ancients - Right Attack Token Horde'),
(3629,'Strand of the Ancients - Left Attack Token Horde'),
(3631,'Strand of the Ancients - Defense Token Horde'),
(3630,'Strand of the Ancients - Defense Token Alliance');


