INSERT INTO worldstate_name(Id, Name) VALUES
(4221,'Isle of Conquest - Alliance Reinforcements Enabled'),
(4222,'Isle of Conquest - Horde Reinforcements Enabled'),
(4226,'Isle of Conquest - Alliance Reinforcements Count'),
(4227,'Isle of Conquest - Horde Reinforcements Count'),
(4317,'Isle of Conquest - Front Gate Horde Closed'),
(4318,'Isle of Conquest - West Gate Horde Closed'),
(4319,'Isle of Conquest - East Gate Horde Closed'),
(4328,'Isle of Conquest - Front Gate Alliance Closed'),
(4327,'Isle of Conquest - West Gate Alliance Closed'),
(4326,'Isle of Conquest - East Gate Alliance Closed'),
(4322,'Isle of Conquest - Front Gate Horde Open'),
(4321,'Isle of Conquest - West Gate Horde Open'),
(4320,'Isle of Conquest - East Gate Horde Open'),
(4323,'Isle of Conquest - Front Gate Alliance Open'),
(4324,'Isle of Conquest - West Gate Alliance Open'),
(4325,'Isle of Conquest - East Gate Alliance Open'),

(4301,'Isle of Conquest - Docks Uncontrolled'),
(4305,'Isle of Conquest - Docks Contested Alliance'),
(4302,'Isle of Conquest - Docks Contested Horde'),
(4304,'Isle of Conquest - Docks Controlled Alliance'),
(4303,'Isle of Conquest - Docks Controlled Horde'),

(4296,'Isle of Conquest - Hangar Uncontrolled'),
(4300,'Isle of Conquest - Hangar Contested Alliance'),
(4297,'Isle of Conquest - Hangar Contested Horde'),
(4299,'Isle of Conquest - Hangar Controlled Alliance'),
(4298,'Isle of Conquest - Hangar Controlled Horde'),

(4294,'Isle of Conquest - Workshop Uncontrolled'),
(4228,'Isle of Conquest - Workshop Contested Alliance'),
(4293,'Isle of Conquest - Workshop Contested Horde'),
(4229,'Isle of Conquest - Workshop Controlled Alliance'),
(4230,'Isle of Conquest - Workshop Controlled Horde'),

(4306,'Isle of Conquest - Quarry Uncontrolled'),
(4310,'Isle of Conquest - Quarry Contested Alliance'),
(4307,'Isle of Conquest - Quarry Contested Horde'),
(4309,'Isle of Conquest - Quarry Controlled Alliance'),
(4308,'Isle of Conquest - Quarry Controlled Horde'),

(4311,'Isle of Conquest - Refinery Uncontrolled'),
(4315,'Isle of Conquest - Refinery Contested Alliance'),
(4312,'Isle of Conquest - Refinery Contested Horde'),
(4314,'Isle of Conquest - Refinery Controlled Alliance'),
(4313,'Isle of Conquest - Refinery Controlled Horde'),

(4341,'Isle of Conquest - Alliance Keep Uncontrolled'),
(4342,'Isle of Conquest - Alliance Keep Contested Alliance'),
(4343,'Isle of Conquest - Alliance Keep Contested Horde'),
(4339,'Isle of Conquest - Alliance Keep Controlled Alliance'),
(4340,'Isle of Conquest - Alliance Keep Controlled Horde'),

(4346,'Isle of Conquest - Horde Keep Uncontrolled'),
(4347,'Isle of Conquest - Horde Keep Contested Alliance'),
(4348,'Isle of Conquest - Horde Keep Contested Horde'),
(4344,'Isle of Conquest - Horde Keep Controlled Alliance'),
(4345,'Isle of Conquest - Horde Keep Controlled Horde');

