
-- ------------------------------------------------------------------------- --

-- last and final fix for Dalaran books (i hope) (WotLK style)

-- The Schools of Arcane Magic - Introduction (OBJECT entry=192708) -- text fix
UPDATE page_text SET text = 'The wondrous gift of magic can be bent to many purposes. We the learned have found that it is easiest to divide the eldritch arts into eight different categories in order to further understand the fundamentals of magic itself. Each of these categories is known as a \'school\' of magic, for they are often learned separately and mages frequently choose to specialize in one type or another. Other mages attempt to master all forms of magic, but few have achieved this lofty goal. Within this tome we will discuss each individual school of magic and some of their notable practitioners.' WHERE entry = '3359';
UPDATE page_text SET text = 'All schools of magic can be combined to create formidable spells that utilize multiple sources of power. Some of these potent spells are discussed later in this series of books, but beware, combining multiple types of magic can be extremely dangerous - especially for beginners.\r\n\r\n	Here you will learn the basics of all schools of magic. Please remember that magic is not to be abused. Do not practice magic without the appropriate supervision.' WHERE entry = '3360';

-- The Schools of Arcane Magic - Abjuration (OBJECT entry=192709) -- text fix
UPDATE page_text SET text = '<Penned by the skilled hand of Archmage Ansirem Runeweaver>' WHERE entry = '3361';
UPDATE page_text SET text = 'Abjuration is the study of protective magic and one of the most important schools for a young mage to study. The most generalized abjuration spell is the mana shield, a spell that transmutes raw mana into a barrier that protects the caster from attacks. Properly executed, this spell can protect the mage against even the most formidable of attacks - but the mana shield is very difficult for a novice to master. It often takes a mage months of practice to even conjure a simple mana shield, and thus, more basic alternatives exist.\r\n' WHERE entry = '3362';
UPDATE page_text SET text = 'A series of \'elemental armor\' spells were invented to aid the traveling mage in the unfortunate case that he or she might be attacked. These spells require far less raw energy to cast than a mana shield and are more easily maintained over time, but lack the raw potency of the mana shield. Rather than stopping an attack completely, a frost armor spell might simply decrease the effectiveness of the assault. The more advanced armor spells grant other benefits - for example, the potent mage armor spell actually assists the caster in regaining magical power more easily.' WHERE entry = '3363';
UPDATE page_text SET text = 'Practitioners of the arcane arts are often ambitious, and we frequently find ourselves in situations where magic may slip just slightly beyond our control. It is for this reason that the \'Ward\' spells exist. Ward spells are quick, potent incantations to protect the caster against a form of elemental damage - damage which is often caused by the caster attempting one of the other schools of magic. This is why studying abjuration early is so imperative.' WHERE entry = '3364';
UPDATE page_text SET text = 'One of the most renowned practitioners of Abjuration magic is Prince Kael\'thas Sunstrider. While the prince is quite formidable in all schools of magic, Kael\'thas has created a variation of Mana Shield that is practically unsurpassed in among the residents of Dalaran. Also notable is the Arcanist Doan, who has perfected a spell that combines Evocation and Abjuration to shield himself for a short time while preparing a powerful area-of-effect spell. This \'Detonate\' spell provides Doan with a degree of near invulnerability for a precious few seconds, but few mages have the capacity to cast it safely.' WHERE entry = '3365';

-- The Schools of Arcane Magic - Divination (OBJECT entry=192711) -- text fix
UPDATE page_text SET text = 'I\'d like to take this time to remind my apprentices that scrying pools are not a toy. They are absolutely not to be used for displaying students of the opposite sex on a \'pay per view\' basis. Consider this your last warning.' WHERE entry = '3372';

-- The Old Wizard's Almanac (OBJECT entry=192905) -- text fix
UPDATE page_text SET text = 'Magnataur - The enormous magnataur have little to no magical affinity.  Magnataur casters are very rare, and tend to be follow a shamanic route if they practice magic at all.  I can tell you first-hand, however, that they won\'t go down without a fight, and their thick hides can withstand several of the most powerful frostbolts.\n\nVrykul - While Northrend\'s half-giants naturally know little to no magic, some have been trained in necromancy by the Lich King. I have also heard rumors of \'rune magic\' of some kind, but I have not yet had the opportunity to research this intriguing subject in depth.\n' WHERE entry = '3534';

-- The Archmage Antonidas - Part I (OBJECT entry=192870) -- text fix
UPDATE page_text SET text = 'At the age of 12, Antonidas\' thesis, \'The Ramifications of Refining Reverse Time Travel Phenomena into Quantifiable Magical Practice\' earned him the Kirin Tor Sash of Supreme Acumen, the youngest ever to receive the award. Shortly thereafter the Ruling Council offered him official placement in the Kirin Tor Advanced Research and Illumination Sect, also the youngest to receive an official invitation.' WHERE entry = '3404';
UPDATE page_text SET text = 'After the Second War, Antonidas investigated the lethargy of the orcs.  The archmage published several theses on his research:\r\n\r\n\'The Causality of War: A Comprehensive Study on Orc Lassitude.\'\r\n\r\n\'The Contrast of Orc Tradition, Sociology, and Psychological Practices from Before and After the Second War.\'\r\n\r\n\'Empirical Study on the Formulation and History of High Profile Fel Magics, and their Relation to the Orc Race.\'' WHERE entry = '3407';

-- STAY OUT!!! (OBJECT entry=192890) -- text fix
UPDATE page_text SET text = '...It\'s not so much an echo as it is a comforting voice in my head, reassuring me that there\'s more to come.  It feels like the opposite of a headache (if that makes any sense), a wave of warmth and ideas.  For example: I knew the librarian kept some materials secret, but the voice tells me she has demonic literature and that even so, her understanding of demons is laughable at best.\r\n' WHERE entry = '3491';

-- --------------------------------------------------------------------------------- --

-- PageText-Entry corrected , fix for missing / wrong texts

UPDATE `item_template` SET `PageText` = 3079 WHERE `entry` = 37540;

-- The Diary of High General Abbendis (ITEM entry=37540) (for Horde) [25 pages]
-- https://www.wowhead.com/wotlk/item=37540/the-diary-of-high-general-abbendis
DELETE FROM page_text WHERE entry in (3079, 3080, 3081, 3082, 3084, 3085, 3086, 3087, 3088, 3089, 3090, 3130, 3131, 3132, 3133, 3134, 3135, 3136, 3137, 3138, 3139, 3140, 3141, 3142, 3557);
INSERT INTO page_text VALUES ('3079','<HTML>\r\n<BODY>\r\n<H1 align=\"center\">The Diary of High General Abbendis</H1>\r\n<BR/>\r\n<IMG src=\"Interface\\FlavorImages\\ScarletCrusadeLogo\"/>\r\n</BODY>\r\n</HTML>', '3080');
INSERT INTO page_text VALUES ('3080','<HTML>\r\n<BODY>\r\n<P>The voice whispered, \"Come to me.\" From the very beginning I knew that it was the Holy Light speaking to me in dreams. At last! After all of my years of prayers and good deeds, the cleansing of the blight of the unliving from the face of Azeroth. After all of the failures and resurrections.</P>\r\n<BR/>\r\n<P>Finally!</P>\r\n</BODY>\r\n</HTML>', '3081');
INSERT INTO page_text VALUES ('3081','<HTML>\r\n<BODY>\r\n<P>It happened again. \"Come to me...\", the Light commanded.</P>\r\n<BR/>\r\n<P>I woke up freezing, but it wasn\'t cold in my chambers. I\'m going to redouble my efforts! I\'ll tell the high abbot tomorrow that I want prayers increased. No more half-measures!</P>\r\n<BR/>\r\n<P>The Holy Light has taken notice of our good work. I can feel it!</P>\r\n</BODY>\r\n</HTML>', '3082');
INSERT INTO page_text VALUES ('3082','<HTML>\r\n<BODY>\r\n<P>This time I was awake! It was very vivid, and yet for over a minute, in the middle of the warm, sunny day, my breath came out misted and chill. One of the priests noticed and dropped to his knees in prayer.</P>\r\n<BR/>\r\n<P>No one else heard the voice, though. At least the witness proves that I\'m not going insane. Maybe I should ask Landgren to pray on the matter?</P>\r\n<BR/>\r\n<P>I\'ll get Jordan and Street to scrutinize their recruiting efforts tomorrow. We\'ve grown bloated with ranks of unbelievers who yearn only to destroy the undead. That\'s not enough!</P>\r\n</BODY>\r\n</HTML>', '3084');
INSERT INTO page_text VALUES ('3084','<HTML>\r\n<BODY>\r\n<P>The commander and the bishop were both receptive. Not that they had any choice. Bishop Street in particular seemed very enthusiastic. He spoke of a revival for the crusade and swore to ferret out the weak of faith within our ranks.</P>\r\n<BR/>\r\n<P>I told him to go easy. I\'ve no intention of destroying the Crusade. However, I do like the sound of forming an elite cadre of the most faithful to do the Light\'s bidding in Northrend. I fear the man\'s friendship with LeCraft is slowly twisting him. They both have their uses, though.</P>\r\n</BODY>\r\n</HTML>', '3085');
INSERT INTO page_text VALUES ('3085','<HTML>\r\n<BODY>\r\n<P>I will leave most of the Crusade here to continue mopping-up operations on the undead in our backyard. I imagine that once they have finished what we began, most will disband and go back to their homes to live in peace.</P>\r\n<BR/>\r\n<P>That somehow seems right. At our finest, we have always been the salt of the earth, rising up to take back our homes from the filth of the Scourge corruption, to return our Lordaeron to its former glory. To a time before the Scourge, before Arthas and regicide... before the Lich King.</P>\r\n</BODY>\r\n</HTML>', '3086');
INSERT INTO page_text VALUES ('3086','<HTML>\r\n<BODY>\r\n<P>There have been whispers amongst the men about a day soon to come that will change everything for the Scarlet Crusade. Bishop Street has put a name to it, calling it the Crimson Dawn.</P>\r\n<BR/>\r\n<P>I will put some thought to this, though I can feel the truth of it in my bones. I pray that it will bring weal for us rather than woe.</P>\r\n</BODY>\r\n</HTML>', '3087');
INSERT INTO page_text VALUES ('3087','<HTML>\r\n<BODY>\r\n<P>The Light has spoken again with a great deal of urgency. I came away from the dream with a sense of impatience. I will not disappoint. There must be no more delays. We must soon be underway!</P>\r\n<BR/>\r\n<P>What a great coincidence then - and I had to control myself from showing my relief - this afternoon Captain Shely procured for us a number of new ships for the voyage. Perhaps it was no coincidence at all? The Holy Light expresses its will in ways that we are not meant to understand.</P>\r\n<BR/>\r\n<P>I will take the Sinner\'s Folly as my flag. I think the name is most fitting.</P>\r\n</BODY>\r\n</HTML>', '3088');
INSERT INTO page_text VALUES ('3088','<HTML>\r\n<BODY>\r\n<P>Now I know why the Light has been pushing me to be underway. In the dead of night a Scourge necropolis appeared in the sky over us and out poured the minions of hell!</P>\r\n<BR/>\r\n<P>A new breed of death knight leads the assault. Already the casualties we\'ve suffered have been catastrophic. With the Scourge able to strike at us anywhere and at will from above, there seems no way to mount a proper defense.</P>\r\n<BR/>\r\n<P>I fear that our intended expedition to Northrend is over before it has begun.</P>\r\n</BODY>\r\n</HTML>', '3089');
INSERT INTO page_text VALUES ('3089','<HTML>\r\n<BODY>\r\n<P>I\'ve been informed that Hearthglen and the surrounding area have already begun to assemble a host. High Commander Galvar Pureblood himself intends to lead them to save us. His efforts will be for naught.</P>\r\n<BR/>\r\n<P>I must see to it that my best couriers get through the enemy lines and warn him off. Hearthglen must prepare to dig in and rally the rest of the Crusade.</P>\r\n<BR/>\r\n<P>With any luck they\'ll get through before nightfall.</P>\r\n</BODY>\r\n</HTML>', '3090');
INSERT INTO page_text VALUES ('3090','<HTML>\r\n<BODY>\r\n<P>There\'s been no word from any of my couriers this morning. It\'s clear that none of them made it through to Hearthglen. The Plaguelands are lost. Pureblood will come with his forces and they\'ll be annihilated out in the open.</P>\r\n<BR/>\r\n<P>This afternoon I received a vision from the Light. In it, I saw the utter destruction of everything that we\'ve built here. The message was clear - I was being told to take the remainder of the most faithful and abandon the Crusade to their doom.</P>\r\n</BODY>\r\n</HTML>', '3130');
INSERT INTO page_text VALUES ('3130','<HTML>\r\n<BODY>\r\n<P>Landgren later told me that he\'d received the same vision. I cannot comprehend how the Light would tell us to take such a dishonorable action, but it is not my place to question - I am to obey, and obey I shall.</P>\r\n<BR/>\r\n<P>It was with trepidation that I gazed upon New Avalon, I suspect for the last time. Our fate lies in Northrend. I am filled with a sense of ominous foreboding for some reason. The mission ahead should shake away these concerns. I will put them out of my mind.</P>\r\n</BODY>\r\n</HTML>', '3131');
INSERT INTO page_text VALUES ('3131','<HTML>\r\n<BODY>\r\n<P>Perhaps with luck, High Commander Pureblood will somehow endure and marshal the survivors. I\'m a coward - a dog running away with my tail tucked between my legs!</P>\r\n<BR/>\r\n<P>Two months they tell me that this journey is going to take. The other ships aren\'t built for speed like the Folly. They\'re carrying most of our forces and equipment, and they\'re not much more than single sail freighters, but they\'ll get there safely.</P>\r\n<BR/>\r\n<P>I\'m not looking forward to this, but for the Light I will endure the sea sickness. I simply mustn\'t let the others see.</P>\r\n</BODY>\r\n</HTML>', '3132');
INSERT INTO page_text VALUES ('3132','<HTML>\r\n<BODY>\r\n<P>I\'ve not written in a while. It\'s as much as I can do to stand upright and not get sick. The men are beginning to wonder why I keep myself holed up in my cabin most of the time. It wouldn\'t be good for morale for them to see me this way.</P>\r\n<BR/>\r\n<P>It shouldn\'t be long now. I pray that it won\'t be. Six weeks already and every day it seems that the weather gets worse. I can only hope that Northrend itself does not have such horrible weather. I wasn\'t built for the cold.</P>\r\n<BR/>\r\n<P>The Holy Light has been silent for a very long time.</P>\r\n</BODY>\r\n</HTML>', '3133');
INSERT INTO page_text VALUES ('3133','<HTML>\r\n<BODY>\r\n<P>We were attacked with no warning whatsoever! Giants in massive oared longships came out of the mist like ghosts! They were silent as the dead.</P>\r\n<BR/>\r\n<P>I lost a ship and all of the men on it. We fought with great courage and skill considering that we have only the most rudimentary naval combat training.</P>\r\n<BR/>\r\n<P>Afterward, the screams of our men who\'d been taken captive by the giants echoed across the water. After a while it grew silent again. Bishop Street led the men in prayers.</P>\r\n</BODY>\r\n</HTML>', '3134');
INSERT INTO page_text VALUES ('3134','<HTML>\r\n<BODY>\r\n<P>I awoke this morning in the middle of making adjustments to my maps. The Light was guiding my hand, showing me exactly where we must go.</P>\r\n<BR/>\r\n<P>We are close!</P>\r\n</BODY>\r\n</HTML>', '3135');
INSERT INTO page_text VALUES ('3135','<HTML>\r\n<BODY>\r\n<P>Landfall!</P>\r\n<BR/>\r\n<P>Exiting the rowboat upon the beach, I planted our banner and was overcome by the Holy Light, which spoke through me. Today is the Crimson Dawn - the great day that we\'ve waited for. This is to be the site of New Hearthglen. We are no longer the Scarlet Crusade. We are now the Scarlet Onslaught!</P>\r\n<BR/>\r\n<P>And an onslaught upon Northrend we shall be! The cancer of the Scourge threatens to overflow in the crown of the world and drown the rest of us. The time has come to take the fight directly to the Lich King\'s doorstep!</P>\r\n</BODY>\r\n</HTML>', '3136');
INSERT INTO page_text VALUES ('3136','<HTML>\r\n<BODY>\r\n<P>It\'s been almost a month now and construction has proceeded apace. I\'ve been too busy to write. My scouts tell me that this land is full of dragons and other strange beasts. We\'ll keep to ourselves until we\'re ready.</P>\r\n<BR/>\r\n<P>In the middle of services today, the high abbot proclaimed that a visitor would arrive soon - one that the Light was sending to lead us to victory.</P>\r\n<BR/>\r\n<P>I don\'t know how I feel about that. Why didn\'t the Light tell me? Have I not served faithfully? Now I\'m to be replaced by some outsider?</P>\r\n</BODY>\r\n</HTML>', '3137');
INSERT INTO page_text VALUES ('3137','<HTML>\r\n<BODY>\r\n<P>Admiral Barean Westwind showed up on my doorstep tonight! By all accounts he\'d died upon these shores an age ago.</P>\r\n<BR/>\r\n<P>He didn\'t look old enough and yet I knew that it was him. He claimed that he was the only survivor of his doomed fleet and that he\'d survived only through the good graces of the Light.</P>\r\n</BODY>\r\n</HTML>', '3138');
INSERT INTO page_text VALUES ('3138','<HTML>\r\n<BODY>\r\n<P>We stayed up speaking through the night and into the morning. He assured me that he had no intention of taking my place, but that the Light had instructed him to travel across the Great Dragonblight to serve as my advisor and commander in title only. He claimed that great change was coming to Northrend. The Alliance and the Horde were going to come en masse in response to a great plague that the Lich King was about to unleash upon them.</P>\r\n</BODY>\r\n</HTML>', '3139');
INSERT INTO page_text VALUES ('3139','<HTML>\r\n<BODY>\r\n<P>The men have taken to the grand admiral with great zeal, especially High Abbot Landgren and Bishop Street. Apparently the Holy Light whispered a new blessing to the admiral in his sleep, which he passed on to Landgren. Some of the men have converted to the priesthood and are now being called \"raven priests\".</P>\r\n<BR/>\r\n<P>Only Jordan seems unimpressed. I suppose that\'s understandable. He probably feels his position is threatened if mine is.</P>\r\n</BODY>\r\n</HTML>', '3140');
INSERT INTO page_text VALUES ('3140','<HTML>\r\n<BODY>\r\n<P>Something doesn\'t seem right. I can\'t put my finger on it, but I cannot make myself fully trust the admiral. He\'s done nothing wrong. Quite the contrary! And yet, I have to trust my gut.</P>\r\n<BR/>\r\n<P>I will pray for understanding. The Light delivered the admiral to lead us to victory and it is not my place to question its decisions. I will continue to obey. I am faithful.</P>\r\n</BODY>\r\n</HTML>', '3141');
INSERT INTO page_text VALUES ('3141','<HTML>\r\n<BODY>\r\n<P>Another couple of months have passed. We\'ve made great strides in the construction of New Hearthglen. The wall is almost complete as is the barracks. Kaleiki\'s men are miracle workers.</P>\r\n<BR/>\r\n<P>My heart hasn\'t been into writing. I\'ve been avoiding putting my thoughts here for some reason. The Light hasn\'t visited me of late, though the admiral assures me that this is nothing to worry about.</P>\r\n</BODY>\r\n</HTML>', '3142');
INSERT INTO page_text VALUES ('3142','<HTML>\r\n<BODY>\r\n<P>My men report that a small group of Forsaken have broken ground on a camp along the hillside to the north. On the other side of the hill, the Alliance have apparently begun the construction of a much larger base.</P>\r\n<BR/>\r\n<P>The admiral says that we should leave them be. There are other Horde forces gathered to the west that would surely come to their aid if we were to attack. I don\'t feel good about it, but I see the logic in his reasoning.</P>\r\n</BODY>\r\n</HTML>', '3557');
INSERT INTO page_text VALUES ('3557','<HTML>\r\n<BODY>\r\n<P>The first phase of construction is done. Admiral Westwind has ordered a group of my men to establish a toehold further to the north. He wouldn\'t go into detail, claiming that he was being \"guided\" to do so.</P>\r\n<BR/>\r\n<P>We caught four spies from the Forsaken town, Venomspite, this afternoon. I\'m going to have LeCraft torture them for information. If we only caught four, how many more have slipped in amongst us?</P>\r\n<BR/>\r\n<P>Why do I feel as if things are beginning to unravel?</P>\r\n</BODY>\r\n</HTML>', '0');

-- --------------------------------------------------------------------------------- --

-- The Path of Redemption (ITEM entry=37931) (for Alliance) [25 pages]
-- https://www.wowhead.com/wotlk/item=37931/the-path-of-redemption
DELETE FROM page_text WHERE entry in (3092, 3093, 3094, 3095, 3096, 3097, 3098, 3099, 3100, 3101, 3143, 3144, 3145, 3146, 3147, 3148, 3149, 3150, 3151, 3152, 3153, 3154, 3155, 3156, 3558);
INSERT INTO page_text VALUES ('3092','<HTML>\r\n<BODY>\r\n<H1 align=\"center\">The Diary of High General Abbendis</H1>\r\n<BR/>\r\n<IMG src=\"Interface\\FlavorImages\\ScarletCrusadeLogo\"/>\r\n</BODY>\r\n</HTML>\r\n', '3093');
INSERT INTO page_text VALUES ('3093','<HTML>\r\n<BODY>\r\n<P>The voice whispered, \"Come to me.\" From the very beginning I knew that it was the Holy Light speaking to me in dreams. At last! After all of my years of prayers and good deeds, the cleansing of the blight of the unliving from the face of Azeroth. After all of the failures and resurrections.</P>\r\n<BR/>\r\n<P>Finally!</P>\r\n</BODY>\r\n</HTML>\r\n\r\n', '3094');
INSERT INTO page_text VALUES ('3094','<HTML>\r\n<BODY>\r\n<P>It happened again. \"Come to me...\", the Light commanded.</P>\r\n<BR/>\r\n<P>I woke up freezing, but it wasn\'t cold in my chambers. I\'m going to redouble my efforts! I\'ll tell the high abbot tomorrow that I want prayers increased. No more half-measures!</P>\r\n<BR/>\r\n<P>The Holy Light has taken notice of our good work. I can feel it!</P>\r\n</BODY>\r\n</HTML>\r\n\r\n', '3095');
INSERT INTO page_text VALUES ('3095','<HTML>\r\n<BODY>\r\n<P>This time I was awake! It was very vivid, and yet for over a minute, in the middle of the warm, sunny day, my breath came out misted and chill. One of the priests noticed and dropped to his knees in prayer.</P>\r\n<BR/>\r\n<P>No one else heard the voice, though. At least the witness proves that I\'m not going insane. Maybe I should ask Landgren to pray on the matter?</P>\r\n<BR/>\r\n<P>I\'ll get Jordan and Street to scrutinize their recruiting efforts tomorrow. We\'ve grown bloated with ranks of unbelievers who yearn only to destroy the undead. That\'s not enough!</P>\r\n</BODY>\r\n</HTML>\r\n\r\n', '3096');
INSERT INTO page_text VALUES ('3096','<HTML>\r\n<BODY>\r\n<P>The commander and the bishop were both receptive. Not that they had any choice. Bishop Street in particular seemed very enthusiastic. He spoke of a revival for the crusade and swore to ferret out the weak of faith within our ranks.</P>\r\n<BR/>\r\n<P>I told him to go easy. I\'ve no intention of destroying the Crusade. However, I do like the sound of forming an elite cadre of the most faithful to do the Light\'s bidding in Northrend. I fear the man\'s friendship with LeCraft is slowly twisting him. They both have their uses, though.</P>\r\n</BODY>\r\n</HTML>', '3097');
INSERT INTO page_text VALUES ('3097','<HTML>\r\n<BODY>\r\n<P>I will leave most of the Crusade here to continue mopping-up operations on the undead in our backyard. I imagine that once they have finished what we began, most will disband and go back to their homes to live in peace.</P>\r\n<BR/>\r\n<P>That somehow seems right. At our finest, we have always been the salt of the earth, rising up to take back our homes from the filth of the Scourge corruption, to return our Lordaeron to its former glory. To a time before the Scourge, before Arthas and regicide... before the Lich King.</P>\r\n</BODY>\r\n</HTML>\r\n\r\n', '3098');
INSERT INTO page_text VALUES ('3098','<HTML>\r\n<BODY>\r\n<P>There have been whispers amongst the men about a day soon to come that will change everything for the Scarlet Crusade. Bishop Street has put a name to it, calling it the Crimson Dawn.</P>\r\n<BR/>\r\n<P>I will put some thought to this, though I can feel the truth of it in my bones. I pray that it will bring weal for us rather than woe.</P>\r\n</BODY>\r\n</HTML>\r\n', '3099');
INSERT INTO page_text VALUES ('3099','<HTML>\r\n<BODY>\r\n<P>The Light has spoken again with a great deal of urgency. I came away from the dream with a sense of impatience. I will not disappoint. There must be no more delays. We must soon be underway!</P>\r\n<BR/>\r\n<P>What a great coincidence then - and I had to control myself from showing my relief - this afternoon Captain Shely procured for us a number of new ships for the voyage. Perhaps it was no coincidence at all? The Holy Light expresses its will in ways that we are not meant to understand.</P>\r\n<BR/>\r\n<P>I will take the Sinner\'s Folly as my flag. I think the name is most fitting.</P>\r\n</BODY>\r\n</HTML>\r\n\r\n', '3100');
INSERT INTO page_text VALUES ('3100','<HTML>\r\n<BODY>\r\n<P>Now I know why the Light has been pushing me to be underway. In the dead of night a Scourge necropolis appeared in the sky over us and out poured the minions of hell!</P>\r\n<BR/>\r\n<P>A new breed of death knight leads the assault. Already the casualties we\'ve suffered have been catastrophic. With the Scourge able to strike at us anywhere and at will from above, there seems no way to mount a proper defense.</P>\r\n<BR/>\r\n<P>I fear that our intended expedition to Northrend is over before it has begun.</P>\r\n</BODY>\r\n</HTML>\r\n\r\n', '3101');
INSERT INTO page_text VALUES ('3101','<HTML>\r\n<BODY>\r\n<P>I\'ve been informed that Hearthglen and the surrounding area have already begun to assemble a host. High Commander Galvar Pureblood himself intends to lead them to save us. His efforts will be for naught.</P>\r\n<BR/>\r\n<P>I must see to it that my best couriers get through the enemy lines and warn him off. Hearthglen must prepare to dig in and rally the rest of the Crusade.</P>\r\n<BR/>\r\n<P>With any luck they\'ll get through before nightfall.</P>\r\n</BODY>\r\n</HTML>\r\n', '3143');
INSERT INTO page_text VALUES ('3143','<HTML>\r\n<BODY>\r\n<P>There\'s been no word from any of my couriers this morning. It\'s clear that none of them made it through to Hearthglen. The Plaguelands are lost. Pureblood will come with his forces and they\'ll be annihilated out in the open.</P>\r\n<BR/>\r\n<P>This afternoon I received a vision from the Light. In it, I saw the utter destruction of everything that we\'ve built here. The message was clear - I was being told to take the remainder of the most faithful and abandon the Crusade to their doom.</P>\r\n</BODY>\r\n</HTML>\r\n', '3144');
INSERT INTO page_text VALUES ('3144','<HTML>\r\n<BODY>\r\n<P>Landgren later told me that he\'d received the same vision. I cannot comprehend how the Light would tell us to take such a dishonorable action, but it is not my place to question - I am to obey, and obey I shall.</P>\r\n<BR/>\r\n<P>It was with trepidation that I gazed upon New Avalon, I suspect for the last time. Our fate lies in Northrend. I am filled with a sense of ominous foreboding for some reason. The mission ahead should shake away these concerns. I will put them out of my mind.</P>\r\n</BODY>\r\n</HTML>\r\n', '3145');
INSERT INTO page_text VALUES ('3145','<HTML>\r\n<BODY>\r\n<P>Perhaps with luck, High Commander Pureblood will somehow endure and marshal the survivors. I\'m a coward - a dog running away with my tail tucked between my legs!</P>\r\n<BR/>\r\n<P>Two months they tell me that this journey is going to take. The other ships aren\'t built for speed like the Folly. They\'re carrying most of our forces and equipment, and they\'re not much more than single sail freighters, but they\'ll get there safely.</P>\r\n<BR/>\r\n<P>I\'m not looking forward to this, but for the Light I will endure the sea sickness. I simply mustn\'t let the others see.</P>\r\n</BODY>\r\n</HTML>\r\n', '3146');
INSERT INTO page_text VALUES ('3146','<HTML>\r\n<BODY>\r\n<P>I\'ve not written in a while. It\'s as much as I can do to stand upright and not get sick. The men are beginning to wonder why I keep myself holed up in my cabin most of the time. It wouldn\'t be good for morale for them to see me this way.</P>\r\n<BR/>\r\n<P>It shouldn\'t be long now. I pray that it won\'t be. Six weeks already and every day it seems that the weather gets worse. I can only hope that Northrend itself does not have such horrible weather. I wasn\'t built for the cold.</P>\r\n<BR/>\r\n<P>The Holy Light has been silent for a very long time.</P>\r\n</BODY>\r\n</HTML>\r\n', '3147');
INSERT INTO page_text VALUES ('3147','<HTML>\r\n<BODY>\r\n<P>We were attacked with no warning whatsoever! Giants in massive oared longships came out of the mist like ghosts! They were silent as the dead.</P>\r\n<BR/>\r\n<P>I lost a ship and all of the men on it. We fought with great courage and skill considering that we have only the most rudimentary naval combat training.</P>\r\n<BR/>\r\n<P>Afterward, the screams of our men who\'d been taken captive by the giants echoed across the water. After a while it grew silent again. Bishop Street led the men in prayers.</P>\r\n</BODY>\r\n</HTML>\r\n', '3148');
INSERT INTO page_text VALUES ('3148','<HTML>\r\n<BODY>\r\n<P>I awoke this morning in the middle of making adjustments to my maps. The Light was guiding my hand, showing me exactly where we must go.</P>\r\n<BR/>\r\n<P>We are close!</P>\r\n</BODY>\r\n</HTML>\r\n', '3149');
INSERT INTO page_text VALUES ('3149','<HTML>\r\n<BODY>\r\n<P>Landfall!</P>\r\n<BR/>\r\n<P>Exiting the rowboat upon the beach, I planted our banner and was overcome by the Holy Light, which spoke through me. Today is the Crimson Dawn - the great day that we\'ve waited for. This is to be the site of New Hearthglen. We are no longer the Scarlet Crusade. We are now the Scarlet Onslaught!</P>\r\n<BR/>\r\n<P>And an onslaught upon Northrend we shall be! The cancer of the Scourge threatens to overflow in the crown of the world and drown the rest of us. The time has come to take the fight directly to the Lich King\'s doorstep!</P>\r\n</BODY>\r\n</HTML>', '3150');
INSERT INTO page_text VALUES ('3150','<HTML>\r\n<BODY>\r\n<P>It\'s been almost a month now and construction has proceeded apace. I\'ve been too busy to write. My scouts tell me that this land is full of dragons and other strange beasts. We\'ll keep to ourselves until we\'re ready.</P>\r\n<BR/>\r\n<P>In the middle of services today, the high abbot proclaimed that a visitor would arrive soon - one that the Light was sending to lead us to victory.</P>\r\n<BR/>\r\n<P>I don\'t know how I feel about that. Why didn\'t the Light tell me? Have I not served faithfully? Now I\'m to be replaced by some outsider?</P>\r\n</BODY>\r\n</HTML>\r\n', '3151');
INSERT INTO page_text VALUES ('3151','<HTML>\r\n<BODY>\r\n<P>Admiral Barean Westwind showed up on my doorstep tonight! By all accounts he\'d died upon these shores an age ago.</P>\r\n<BR/>\r\n<P>He didn\'t look old enough and yet I knew that it was him. He claimed that he was the only survivor of his doomed fleet and that he\'d survived only through the good graces of the Light.</P>\r\n</BODY>\r\n</HTML>', '3152');
INSERT INTO page_text VALUES ('3152','<HTML>\r\n<BODY>\r\n<P>We stayed up speaking through the night and into the morning. He assured me that he had no intention of taking my place, but that the Light had instructed him to travel across the Great Dragonblight to serve as my advisor and commander in title only. He claimed that great change was coming to Northrend. The Alliance and the Horde were going to come en masse in response to a great plague that the Lich King was about to unleash upon them.</P>\r\n</BODY>\r\n</HTML>', '3153');
INSERT INTO page_text VALUES ('3153','<HTML>\r\n<BODY>\r\n<P>The men have taken to the grand admiral with great zeal, especially High Abbot Landgren and Bishop Street. Apparently the Holy Light whispered a new blessing to the admiral in his sleep, which he passed on to Landgren. Some of the men have converted to the priesthood and are now being called \"raven priests\".</P>\r\n<BR/>\r\n<P>Only Jordan seems unimpressed. I suppose that\'s understandable. He probably feels his position is threatened if mine is.</P>\r\n</BODY>\r\n</HTML>\r\n', '3154');
INSERT INTO page_text VALUES ('3154','<HTML>\r\n<BODY>\r\n<P>Something doesn\'t seem right. I can\'t put my finger on it, but I cannot make myself fully trust the admiral. He\'s done nothing wrong. Quite the contrary! And yet, I have to trust my gut.</P>\r\n<BR/>\r\n<P>I will pray for understanding. The Light delivered the admiral to lead us to victory and it is not my place to question its decisions. I will continue to obey. I am faithful.</P>\r\n</BODY>\r\n</HTML>\r\n', '3155');
INSERT INTO page_text VALUES ('3155','<HTML>\r\n<BODY>\r\n<P>Another couple of months have passed. We\'ve made great strides in the construction of New Hearthglen. The wall is almost complete as is the barracks. Kaleiki\'s men are miracle workers.</P>\r\n<BR/>\r\n<P>My heart hasn\'t been into writing. I\'ve been avoiding putting my thoughts here for some reason. The Light hasn\'t visited me of late, though the admiral assures me that this is nothing to worry about.</P>\r\n</BODY>\r\n</HTML>\r\n', '3156');
INSERT INTO page_text VALUES ('3156','<HTML>\r\n<BODY>\r\n<P>My men report that a small group of Forsaken have broken ground on a camp along the hillside to the north. On the other side of the hill, the Alliance have apparently begun the construction of a much larger base.</P>\r\n<BR/>\r\n<P>The admiral says that we should leave them be. There are other Horde forces gathered to the west that would surely come to their aid if we were to attack. I don\'t feel good about it, but I see the logic in his reasoning.</P>\r\n</BODY>\r\n</HTML>', '3558');
INSERT INTO page_text VALUES ('3558','<HTML>\r\n<BODY>\r\n<P>The first phase of construction is done. Admiral Westwind has ordered a group of my men to establish a toehold further to the north. He wouldn\'t go into detail, claiming that he was being \"guided\" to do so.</P>\r\n<BR/>\r\n<P>We caught four spies from the Forsaken town, Venomspite, this afternoon. I\'m going to have LeCraft torture them for information. If we only caught four, how many more have slipped in amongst us?</P>\r\n<BR/>\r\n<P>Why do I feel as if things are beginning to unravel?</P>\r\n</BODY>\r\n</HTML>', '0');

-- --------------------------------------------------------------------------------- --

-- The Path of Redemption (ITEM entry=39654) (for both, DK only) [7 pages]
-- https://www.wowhead.com/wotlk/item=39654/the-path-of-redemption
DELETE FROM page_text WHERE entry in (3121, 3122, 3123, 3124, 3125, 3126, 3129);
INSERT INTO page_text VALUES ('3121','<HTML>\r\n<BODY>\r\n<BR/>\r\n<H1 align=\"center\">The Path of Redemption</H1>\r\n<BR/>\r\n<IMG src=\"Interface\\FlavorImages\\ScarletCrusadeLogo\"/>\r\n</BODY>\r\n</HTML>\r\n', '3122');
INSERT INTO page_text VALUES ('3122','<HTML>\r\n<BODY>\r\n<BR/>\r\n<P>The voice whispered, \"Come to me.\" From the very beginning I knew that it was the Holy Light speaking to me in dreams. At last! After all of my years of prayers and good deeds, the cleansing of the blight of the unliving from the face of Azeroth. After all of the failures and resurrections.</P>\r\n<BR/>\r\n<P>Finally!</P>\r\n</BODY>\r\n</HTML>', '3123');
INSERT INTO page_text VALUES ('3123','<HTML>\r\n<BODY>\r\n<BR/>\r\n<P>It happened again. \"Come to me...\", the Light commanded.</P>\r\n<BR/>\r\n<P>This time I woke up freezing, but it wasn\'t cold in my chambers. I\'m going to redouble my efforts! I\'ll tell the high abbot tomorrow that I want prayers increased. No more half-measures!</P>\r\n<BR/>\r\n<P>The Holy Light has taken notice of our good work. I can feel it!</P>\r\n</BODY>\r\n</HTML>\r\n', '3124');
INSERT INTO page_text VALUES ('3124','<HTML>\r\n<BODY>\r\n<BR/>\r\n<P>This time I was awake! It was very vivid, and yet for over a minute, in the middle of the warm, sunny day, my breath came out misted and chill. One of the priests noticed and dropped to his knees in prayer.</P>\r\n<BR/>\r\n<P>No one else heard the voice, though. At least the witness proves that I\'m not going insane. Maybe I should ask Landgren to pray on the matter?</P>\r\n<BR/>\r\n<P>I\'ll get Jordan and Street to scrutinize their recruiting efforts tomorrow. We\'ve grown bloated with ranks of unbelievers who yearn only to destroy the undead. That\'s not enough!</P>\r\n<BR/>\r\n</BODY>\r\n</HTML>\r\n\r\n\r\n\r\n', '3125');
INSERT INTO page_text VALUES ('3125','The commander and the bishop were both receptive. Not that they had any choice. Bishop Street in particular seemed very enthusiastic. He spoke of a new crusade and swore to ferret out the weak of faith within our ranks.\r\n\r\nI told him to go easy. We\'re not destroying the Crusade so much as forming an elite cadre of the most faithful to do the Light\'s bidding in Northrend. I fear the man\'s friendship with LeCraft is slowly twisting him. They both have their uses, though.\r\n\r\nStreet\'s talk of a new crusade, however, has me thinking. I believe that when this new force is assembled, I will give us a new name. It\'ll have to be evocative of our new mission, yet still provide a tie to the past. I will pray with the high abbot on this.', '3126');
INSERT INTO page_text VALUES ('3126','<HTML>\r\n<BODY>\r\n<BR/>\r\n<P>Our prayers have been answered. The high abbot was particularly moved by the force of the Light\'s voice, its clarity, and sense of purpose.</P>\r\n<BR/>\r\n<P>Those of us going north - the most faithful - shall be known as the Scarlet Onslaught.</P>\r\n<BR/>\r\n<P>And an onslaught upon Northrend we shall be! The cancer of the Scourge threatens to overflow in the crown of the world and drown the rest of us. The time has come to take the fight directly to the Lich King\'s doorstep.</P>\r\n</BODY>\r\n</HTML>\r\n', '3129');
INSERT INTO page_text VALUES ('3129','<HTML>\r\n<BODY>\r\n<BR/>\r\n<P>It is with trepidation that I gaze upon New Avalon, I somehow suspect for the last time. The fate of our cause lies in Northrend. I am filled with a sense of ominous foreboding for some reason. The mission ahead should shake away these concerns. I will put them out of my mind.</P>\r\n<BR/>\r\n<P>The Crimson Dawn is upon us.</P>\r\n</BODY>\r\n</HTML>\r\n', '0');

-- --------------------------------------------------------------------------------- --


